[project]
name = "goit-pythonweb-hw-06"
version = "0.1.0"
description = ""
authors = [
    {name = "YuliiaDubyniuk",email = "yuliia.dubyniuk@gmail.com"}
]
requires-python = ">=3.13"
dependencies = [
    "sqlalchemy (>=2.0.54,<3.0.0)",
    "alembic (>=1.20.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
